apiVersion: vm.platform.org/v1alpha1
kind: VirtualMachineInstance
metadata:
  name: sample-ec2
  namespace: default
spec:
  parameters:
    # small, medium, large
    instanceSize: small
  compositionSelector:
    matchLabels:
      provider: aws
      vpc: new
  writeConnectionSecretToRef:
    name: ec2-conn
